"""tests/memory/e2e/bot/live_rem_faithfulness.py — REAL validation of the REM faithfulness gate (V2-104).

Operator rule (2026-08-16): "all validations have to be real... we do not care about the cost; what matters to us
is verifying that everything works properly." `test_rem.py` tests the MECHANICS of the gate with `verify_fn` mocked
by hand — it never invokes the real model. This script DOES: it calls the REAL
`nucleo.memllm.synthesize_concept_groups()` and `verify_insight_grounded()` (DeepSeek V4 Flash, the production model)
against an isolated database.

Three tests, in order:
  1. REAL SYNTHESIS — a group of real pills → insight generated by the model → do the deterministic gate AND the
     REAL verifier accept it? (clean case; YES is expected)
  2. ADVERSARIAL — an insight fabricated BY HAND (a name and number that are NOT in the pills) → does the REAL
     verifier detect it? (it is expected to reject it — this is the test that demonstrates the gate is not theater)
  3. COMPLETE CYCLE — `memory.rem.synthesize()` with both REAL hooks against the isolated database: does it write
     the insight, demote the sources, and run the entire cycle from end to end without mocks?

Usage: ./.venv/bin/python -m tests.memory.e2e.bot.live_rem_faithfulness
Isolated database: ZAELAR_DB=memory/_data/zaelar.remcheck.db (gitignored; deleted and recreated on every run).
"""
from __future__ import annotations

import os
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[4]


def _setup_env():
    os.environ["ZAELAR_DB"] = str(REPO / "memory" / "_data" / "zaelar.remcheck.db")
    os.environ.setdefault("ZAELAR_LANGUAGE", "es")
    # Operator rule (2026-08-16): "no Ollama anywhere now... everything paid" — work with LOCAL models
    # (Ollama/embeddinggemma) is ON HOLD until the system is validated in production against the paid model; it will
    # then resume with the SAME benchmark. `fastembed` (in-process ONNX, serverless, with no contention with Ollama)
    # is the embeddings backend in the meantime — this test does NOT measure embedding quality; it only needs any
    # vector for `insert_memory()` to work. What is validated here is the REAL synthesis and verification, which are
    # already DeepSeek end to end.
    os.environ["ZAELAR_EMBED_BACKEND"] = "fastembed"
    try:
        from dotenv import load_dotenv
        load_dotenv(REPO / ".env", override=False)
        load_dotenv(REPO / ".meshkore" / "credentials" / "zaelar.env", override=False)
    except Exception:
        pass
    db_path = pathlib.Path(os.environ["ZAELAR_DB"])
    if db_path.exists():
        db_path.unlink()


PILLS = [
    "Los domingos por la mañana sale a correr 8 kilómetros por el parque del Retiro.",
    "Entrena para la media maratón de Madrid, prevista para noviembre.",
    "Le gusta correr con música de Vetusta Morla en los auriculares.",
    "El fisio le recomendó bajar el ritmo tras una molestia en la rodilla derecha.",
    "Corre siempre antes de las nueve para evitar el calor.",
]
CONCEPT = "running"

# Insight fabricated BY HAND: introduces a name ("Manolo") and a number ("21 km") that are NOT in PILLS —
# classic LLM summary fabrication, the kind of error the gate must catch.
FABRICATED_INSIGHT = "Manolo, su compañero de entrenamiento, le acompaña a correr 21 km cada domingo."


def main() -> int:
    _setup_env()
    from memory import db as memdb, writer as memwriter
    from memory.rem import _grounded, synthesize
    from nucleo import memllm

    memdb.get_db()
    # `_canonical_lang_native()` (nucleo/memllm.py) prefers `state.language` over ZAELAR_LANGUAGE — and the
    # DEFAULT state value in a new database is "en" (the product's language startup value, memory/state.py:28).
    # Without this, a newly created isolated database produces insights in ENGLISH even when the pills are in
    # Spanish — this is not a REM bug; this database simply never went through language detection for the operator's
    # first real sentence.
    from memory import state as memstate
    memstate.patch({"language": "es"})
    ok = True

    print("=" * 78)
    print("PRUEBA 1 — síntesis REAL (DeepSeek V4 Flash) sobre píldoras reales")
    print("=" * 78)
    ids = [memwriter.insert_memory(t, level="mid", kind="fact", weight=0.8, concepts=[CONCEPT])
           for t in PILLS]
    group = {"concept": CONCEPT, "pills": PILLS}
    # The gate is STRICT and probabilistic BY DESIGN (fail-closed) — a faithful insight may be rejected because of
    # judge noise in a single attempt. As in Test 3, allow up to 3 real attempts before considering it lost.
    test1_ok = False
    for attempt in range(1, 4):
        results = memllm.synthesize_concept_groups([group])
        if not results or not results[0].get("insight"):
            print(f"  [intento {attempt}/3] el modelo no devolvió insight")
            continue
        real_insight = results[0]["insight"]
        grounded = _grounded(real_insight, PILLS)
        verified = memllm.verify_insight_grounded(real_insight, PILLS)
        print(f"  [intento {attempt}/3] insight={real_insight!r}")
        print(f"               backstop={grounded}  verificación_real={verified}")
        if grounded and verified:
            test1_ok = True
            break
    if test1_ok:
        print("  ✓ al menos un intento real generó un insight aceptado por los dos gates")
    else:
        print("  ✗ FALLO: en 3 intentos reales, ninguno pasó los dos gates")
        ok = False

    print()
    print("=" * 78)
    print("PRUEBA 2 — ADVERSARIAL: ¿el verificador REAL detecta una fabricación a mano?")
    print("=" * 78)
    print(f"  insight fabricado: {FABRICATED_INSIGHT!r}")
    det = _grounded(FABRICATED_INSIGHT, PILLS)
    print(f"  backstop determinista rechaza (debe ser False): {det}")
    real_verify = memllm.verify_insight_grounded(FABRICATED_INSIGHT, PILLS)
    print(f"  verificación REAL por LLM rechaza (debe ser False): {real_verify}")
    if det or real_verify:
        print("  ✗ FALLO: alguno de los dos gates ACEPTÓ una fabricación evidente")
        ok = False
    else:
        print("  ✓ ambos gates (determinista Y modelo real) rechazaron la fabricación")

    print()
    print("=" * 78)
    print("PRUEBA 3 — ciclo completo REAL: memory.rem.synthesize() con hooks reales")
    print("=" * 78)
    before = {mid: memdb.get_db().query_one("SELECT weight FROM memories WHERE id=?", (mid,))["weight"]
              for mid in ids}

    # Full transparency: if the cycle rejects, we want to SEE what the model generated THIS time (generation is
    # stochastic — Test 1 already showed that the model CAN produce an insight that passes both gates; if this
    # independent call does not, that is a real observation to show, not hide).
    def _synthesize_fn_debug(groups):
        out = memllm.synthesize_concept_groups(groups)
        for r in out:
            print(f"  [debug] intento REAL de síntesis: {r}")
        return out

    def _verify_fn_debug(insight, pills):
        v = memllm.verify_insight_grounded(insight, pills)
        print(f"  [debug] verificación REAL sobre ese intento: {v}")
        return v

    # Generation is STOCHASTIC and the gate is STRICT by design (asymmetric: losing a legitimate insight is cheaper
    # than letting an invented one through) — real REM retries the FOLLOWING NIGHT if an attempt does not pass.
    # Here we simulate up to 3 "nights" to demonstrate the genuine happy path without forcing anything.
    written = 0
    for attempt in range(1, 4):
        print(f"  --- intento {attempt}/3 ---")
        written = synthesize(_synthesize_fn_debug, min_group=4, verify_fn=_verify_fn_debug)
        if written:
            break
    print(f"  insights escritos: {written}")
    row = memdb.get_db().query_one("SELECT text, weight FROM memories WHERE slot=? AND valid=1",
                                   (f"insight:{CONCEPT}",))
    if written == 1 and row is not None:
        print(f"  insight vigente: {row['text']!r} (peso {row['weight']})")
        demoted = 0
        for mid in ids:
            after = memdb.get_db().query_one("SELECT weight FROM memories WHERE id=?", (mid,))["weight"]
            if after < before[mid]:
                demoted += 1
        print(f"  píldoras fuente demotadas: {demoted}/{len(ids)}")
        if demoted == len(ids):
            print("  ✓ ciclo completo real: sintetiza, verifica de verdad, escribe y demota")
        else:
            print("  ✗ FALLO: no todas las fuentes quedaron demotadas")
            ok = False
    else:
        print("  ✗ FALLO: no se escribió el insight en el ciclo completo (¿el verificador real lo rechazó?)")
        ok = False

    print()
    print("=" * 78)
    print("RESULTADO:", "✓ TODAS LAS PRUEBAS REALES PASARON" if ok else "✗ HUBO FALLOS — revisar arriba")
    print("=" * 78)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
