"""widgets/producers.py — widgets that PRODUCE something (V2-092): how to stop all at once and who owns the speaker.

`actions.py` answers "HOW is this action executed?" (direct / with confirmation / escalated). This module answers two
other questions, orthogonal to that one and previously ownerless:

    1. Is this widget PRODUCING something right now (playing, recording, processing)?
    2. If it is, how do we tell it to STOP — and can two run at once on the same channel?

## Why a contract is needed instead of one `if` per widget

The bug that exposed it (operator, 2026-08-13): with the agent STOPPED, a YouTube video kept playing, and on top of
that it played at the same time as the music player. It could be fixed with two wired special cases —"if the widget
is youtube, call pause"—, but that does not scale to a catalog where widgets are GENERATED by the agent: next week's
podcast widget would again keep playing over a stopped agent, and nobody would remember to add its `if`.

So production is **DECLARED** in the manifest, just like actions, size, or whether fullscreen is native are already
declared. A declared choice is not misrouted:

    "runtime": {
      "output": "audio",                                    // EXCLUSIVE channel it occupies (omit = no competition)
      "produce": ["load", "play", "restart", "unmute"],      // actions that MAKE it produce
      "suspend": "pause",                                    // action that stops it
      "active_when": {"videoId": true, "paused": false}      // how "is producing" is read from view_data()
    }

`active_when` accepts a LIST of conditions when a widget can produce through more than one path — music can play
through Spotify (remote device) or YouTube-audio (hidden iframe), and those are two different states:

    "active_when": [{"yt.videoId": true, "yt.paused": false}, {"now_playing.playing": true}]

Inside one condition everything must hold (AND); between conditions one is enough (OR).

With this, three capabilities come free for ANY present or future widget:

  - **Global stop** (`suspend_all`): the operator's ⏻ suspends everything producing, without knowing anyone by name.
  - **Channel exclusivity** (`enforce_exclusive`): starting music stops video and vice versa. Two things playing at
    once is not a feature, it is a failure — and there is one speaker.
  - **Stopped-agent gate** (`gate`): a stopped agent starts no playback. Not by voice, not by cron, not by a card
    button.

## Invariantes

  - **`active_when` is evaluated against `view_data()`**, which is the widget's truth (not our copy of its state).
    Dotted paths (`yt.paused`) are supported because a widget may keep playback under a nested block.
  - **Suspending does NOT go through the gate.** It uses the raw path (`server_api.dispatch_raw`): if `suspend` went
    through the same funnel that gates actions, stopping while the agent is stopped would reject itself.
  - **Never raises.** A widget that blows up when queried is considered "not producing" and the fact is logged. Global
    stop cannot fall over because of one broken widget: the operator believes everything stopped while something still
    plays.
"""
from __future__ import annotations

import asyncio

from loguru import logger

from . import runtime

# Default channel for a widget that declares `runtime` without saying which channel it produces on. `""` = competes
# with nobody (it produces, but not on an exclusive resource: a process, a disk recording...). Only a NAMED channel is
# contested; this way declaring production does not impose exclusivity by accident.
_NO_CHANNEL = ""


def spec(w: dict | str) -> dict | None:
    """Widget production contract, normalized, or `None` if it declares none.

    Accepts the full manifest or an id (looked up in the catalog). A `runtime` without `suspend` is useless —there
    would be no way to stop it— and is discarded with a warning: prefer a widget that does not participate over one
    that half-participates and leaves the operator with something playing that the system thinks is stopped."""
    man = runtime.get(w) if isinstance(w, str) else w
    if not isinstance(man, dict):
        return None
    rt = man.get("runtime")
    if not isinstance(rt, dict):
        return None
    wid = str(man.get("id") or "")
    susp = str(rt.get("suspend") or "").strip()
    if not susp:
        logger.warning(f"producers[{wid}]: declara 'runtime' SIN 'suspend' — se ignora (no habría cómo pararlo)")
        return None
    produce = rt.get("produce") or []
    if isinstance(produce, str):
        produce = [produce]
    return {
        "id": wid,
        "output": str(rt.get("output") or _NO_CHANNEL).strip(),
        "produce": {str(a).strip() for a in produce if str(a).strip()},
        "suspend": susp,
        "active_when": _clauses(rt.get("active_when")),
    }


def _clauses(aw) -> list[dict]:
    """Normalize `active_when` to a LIST of conditions (OR of AND). A lone dict is a one-item list.

    EMPTY conditions are discarded: `{}` would always hold (a "for all" over zero fields is true), so a widget that
    forgot to say how to observe it would appear as "producing" FOREVER and global stop would send it a command on
    every pass."""
    if isinstance(aw, dict):
        return [aw] if aw else []
    if isinstance(aw, (list, tuple)):
        return [c for c in aw if isinstance(c, dict) and c]
    return []


def all_specs() -> dict[str, dict]:
    """`{id: spec}` for every catalog widget that declares production."""
    out = {}
    for w in runtime.catalog():
        sp = spec(w)
        if sp and sp["id"]:
            out[sp["id"]] = sp
    return out


def _dig(data: dict, path: str):
    """Read `a.b.c` from a nested dict. `None` if the path does not exist (an absent field is NOT "producing")."""
    cur = data
    for part in str(path).split("."):
        if not isinstance(cur, dict):
            return None
        cur = cur.get(part)
    return cur


def is_producing(data: dict, sp: dict) -> bool:
    """Do the widget data say it is producing NOW? PURE (no I/O) so it can be tested alone.

    ONE `active_when` condition holding is enough, and inside it ALL fields must hold. `true`/`false` compare by
    TRUTH (not identity): `{"paused": false}` = "the paused field is falsy", which is what a widget actually writes
    (`0`, `""`, absent). Any other value compares by text equality, so `{"mode": "youtube"}` works as-is.

    Without `active_when` it cannot be known → `False`. A widget that wants to participate in global stop must say how
    to observe it; guessing would suspend things that were not playing. A degraded `view_data()` (`{"error": ...}`)
    also does not produce: do not send commands to a widget that cannot even read itself."""
    clauses = sp.get("active_when") or []
    if not isinstance(data, dict) or not clauses or data.get("error"):
        return False
    return any(_clause_holds(data, c) for c in clauses)


def _clause_holds(data: dict, cond: dict) -> bool:
    for path, want in cond.items():
        got = _dig(data, path)
        if want is True:
            if not got:
                return False
        elif want is False:
            if got:
                return False
        elif str(got) != str(want):
            return False
    return True


async def _view_data(wid: str) -> dict:
    """Widget `view_data()` with the SAME isolation as the HTTP API (bounded pool + hard timeout)."""
    from . import server_api
    def call(view_data):
        try:
            return view_data(q="")
        except TypeError:                       # old widgets do not accept query
            return view_data()
    res = await server_api.run_widget_hook(wid, "view_data", call)
    return res if isinstance(res, dict) and res is not server_api.MISSING else {}


async def producing(*, channel: str | None = None) -> list[str]:
    """Ids of widgets producing right now (optionally only those on one channel).

    Query `view_data()` in PARALLEL: during global stop the operator cannot wait for N serial timeouts."""
    specs = all_specs()
    if channel is not None:
        specs = {k: v for k, v in specs.items() if v["output"] == channel}
    if not specs:
        return []
    ids = list(specs.keys())
    datas = await asyncio.gather(*[_view_data(w) for w in ids], return_exceptions=True)
    out = []
    for wid, data in zip(ids, datas):
        if isinstance(data, BaseException):
            logger.warning(f"producers[{wid}]: no pude leer su estado ({data!r}) — lo doy por parado")
            continue
        try:
            if is_producing(data, specs[wid]):
                out.append(wid)
        except Exception as e:  # noqa: BLE001
            logger.warning(f"producers[{wid}]: active_when malformado ({e!r}) — lo doy por parado")
    return out


async def suspend(wid: str, sp: dict | None = None, *, reason: str = "") -> bool:
    """Send ONE widget its declared suspension action. RAW path (no gate, no exclusivity) so stopping never rejects
    itself. `True` if the widget accepted it."""
    sp = sp or spec(wid)
    if not sp:
        return False
    from . import server_api
    try:
        res = await server_api.dispatch_raw(wid, sp["suspend"], {"reason": reason})
    except Exception as e:  # noqa: BLE001
        logger.warning(f"producers[{wid}]: falló la suspensión ({sp['suspend']}): {e!r}")
        return False
    if isinstance(res, dict) and (res.get("error") or res.get("ok") is False):
        logger.warning(f"producers[{wid}]: la suspensión ({sp['suspend']}) no se aplicó: {res}")
        return False
    return True


async def suspend_all(*, reason: str = "", channel: str | None = None, keep: str = "") -> list[str]:
    """Suspend EVERY widget that is producing (or only those on `channel`), except `keep`. Return ids that were truly
    suspended — this is shown in the operator log, so it cannot be a list of intentions."""
    specs = all_specs()
    todo = [w for w in await producing(channel=channel) if w != keep]
    if not todo:
        return []
    oks = await asyncio.gather(*[suspend(w, specs.get(w), reason=reason) for w in todo],
                              return_exceptions=True)
    return [w for w, ok in zip(todo, oks) if ok is True]


def starts_production(wid: str, action: str) -> bool:
    """Does this action MAKE this widget PRODUCE? Declared (`runtime.produce`), not inferred."""
    sp = spec(wid)
    return bool(sp and str(action or "").strip() in sp["produce"])


def gate(wid: str, action: str) -> dict | None:
    """Pre-gate before a widget action: `None` = go ahead; a dict = REJECTED, and that dict is the response.

    Single rule: **when the agent is stopped, nothing starts producing.** Operator words: "if the agent is stopped, no
    widget can be running; they can be visible or open, but they cannot be playing anything or doing anything".
    Everything else (navigating the card, creating a list, changing view) remains allowed: stopping the agent does not
    freeze the interface."""
    if not starts_production(wid, action):
        return None
    try:
        from nucleo import runstate
        if not runstate.stopped():
            return None
    except Exception:                            # without runstate there is no reason to block anyone
        return None
    return {"ok": False, "error": "agent_stopped", "id": wid, "action": action,
            "message": "El agente está parado. Enciéndelo (⏻) para volver a reproducir."}


async def enforce_exclusive(wid: str, action: str) -> list[str]:
    """After an action that starts production: if the widget occupies an EXCLUSIVE channel, silence the others there.

    Called AFTER applying the action (not before): who occupies the channel is read from real state, not from what we
    thought the action would do. Returns who was silenced."""
    if not starts_production(wid, action):
        return []
    sp = spec(wid)
    channel = (sp or {}).get("output") or _NO_CHANNEL
    if not channel:
        return []
    others = await suspend_all(reason=f"exclusive:{channel}", channel=channel, keep=wid)
    if others:
        logger.info(f"producers[{wid}]: toma el canal «{channel}» → suspendidos {others}")
        try:
            from voice.observer import emit
            emit("widget", "exclusive", text=f"{wid} toma «{channel}» → calla {', '.join(others)}",
                 extra={"id": wid, "channel": channel, "suspended": others})
        except Exception:
            pass
    return others
