"""
i18n.runtime — the EXECUTION side of the multilingual subsystem (V2-089).

Hot path. Import-cheap, deterministic, NO LLM, NO voice pipeline. This is all the running server needs to serve
UI strings: read the preset bundles from the repo, read generated bundles from the store, report state, and diff
what a language is still missing. Everything that PREPARES a language (detection, translation, upgrades) lives
in i18n.init and is NEVER called from here — that separation is the whole point (see the package docstring).

SINGLE SOURCE OF TRUTH = i18n/bundles/en.json (the English manifest: every UI string key → its English text).
Spanish is the preset translation (es.json). Any other language is generated by i18n.init and read via the store.
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path

from i18n import store as _store

# Coarse cache-buster for the browser's localStorage bundle cache. Bump when the SET of keys or their English
# text changes. (Per-key upgrade diffing uses the English snapshot stored in each generated bundle — see
# i18n.init.ensure; this version is just the frontend cache signal.)
MANIFEST_VERSION = 3   # 2026-08-09: claves del visor — columnas, familias, panel de filtros, abreviaturas

PRESET = ("en", "es")            # shipped in the repo; never generated
BASE = "en"                      # the manifest language every other bundle is translated FROM

_BUNDLES_DIR = Path(__file__).resolve().parent / "bundles"


def _read_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def manifest() -> dict[str, str]:
    """The English base: {key: english text}. The canonical list of translatable UI strings."""
    return _read_json(_BUNDLES_DIR / f"{BASE}.json")


def _preset(code: str) -> dict[str, str] | None:
    p = _BUNDLES_DIR / f"{code}.json"
    return _read_json(p) if p.exists() else None


def strings(code: str) -> dict[str, str]:
    """UI strings for `code`, ready for the frontend. Preset → repo bundle; else → generated bundle's strings
    (empty until i18n.init has produced them; the frontend falls back to English)."""
    code = (code or BASE).strip().lower()
    if code in PRESET:
        return _preset(code) or {}
    return dict((_store.read(code).get("strings") or {}))


def available() -> list[str]:
    """Language codes that have a bundle right now (presets + whatever's been generated)."""
    return sorted(set(PRESET) | set(_store.codes()))


def active_code() -> str:
    """The active OPERATOR/UI language — ANY code (es, en, ar, zh, …), NOT gated by the voice catalog.

    Decoupling (V2-089): the UI can be in any language we can generate a bundle for, so the active UI language is
    the RAW `ZAELAR_LANGUAGE` (what auto-detection / the ⚙ set). The VOICE catalog (voice/engine/core/langs) stays
    es/en — it gates STT recognition + TTS voice, which need per-language models/voices; that's a separate axis.
    They coincide for es/en; for a generated language the UI follows it while voice falls back to the catalog."""
    c = (os.getenv("ZAELAR_LANGUAGE") or "").strip().lower()
    if re.fullmatch(r"[a-z]{2,3}", c):
        return c
    try:
        from voice.engine.core import langs
        return langs.current_code()
    except Exception:
        return BASE


def missing_keys(code: str) -> list[str]:
    """Keys the language still needs: absent, or whose English source changed since it was generated. Presets are
    always complete (→ []). Drives i18n.init.ensure and the 'preparing language' boot veil."""
    code = (code or BASE).strip().lower()
    if code in PRESET:
        return []
    man = manifest()
    gen = _store.read(code)
    have = gen.get("strings", {}) or {}
    src = gen.get("src", {}) or {}
    return [k for k, en_text in man.items() if k not in have or src.get(k) != en_text]


def state() -> dict:
    """What the frontend needs at boot: the active language + which bundles exist + the cache version."""
    return {"active": active_code(), "available": available(), "preset": list(PRESET),
            "version": MANIFEST_VERSION}


def bundle(code: str) -> dict:
    """Serve one bundle to the frontend: {code, version, strings, generated}."""
    code = (code or BASE).strip().lower()
    return {"code": code, "version": MANIFEST_VERSION, "strings": strings(code),
            "generated": code not in PRESET}
