"""A failure swallowed in silence only gets RARER (V2-778 F2-20, 2026-10-01).

The audit counted the `except …: pass` handlers in product code — a failure that exits EMPTY, the class this house
names as the worst, because nothing distinguishes «it failed» from «there was nothing to do». They had grown by
217 in the demo week alone. This ratchet freezes today's count per file: a file may not gain a swallow-only
handler, and the total may only fall. The fix for one is a `_note`/`emit` that says what failed, not a comment.

Counted by AST over tracked product files (tests excluded): an `except` whose whole body is `pass` (or `...`).
"""
from __future__ import annotations

import ast
import subprocess
from pathlib import Path

ENGINE = Path(__file__).resolve().parents[3]


def _counts() -> dict[str, int]:
    out = subprocess.run(["git", "ls-files", "*.py"], cwd=ENGINE, capture_output=True, text=True).stdout.split()
    counts: dict[str, int] = {}
    for rel in out:
        if rel.startswith("tests/") or "/tests/" in rel:
            continue
        p = ENGINE / rel
        if not p.exists():
            continue
        try:
            tree = ast.parse(p.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError):
            continue
        n = 0
        for node in ast.walk(tree):
            if isinstance(node, ast.ExceptHandler) and all(
                    isinstance(b, ast.Pass) or (isinstance(b, ast.Expr) and isinstance(b.value, ast.Constant)
                                                and b.value.value is Ellipsis) for b in node.body):
                n += 1
        if n:
            counts[rel] = n
    return counts


#: Measured on 2026-10-01 — the TOTAL may only fall, and no file may exceed its own count.
TOTAL = 1147
PER_FILE: dict[str, int] = {
    'bus/__init__.py': 5,
    'bus/log.py': 6,
    'bus/sse.py': 1,
    'config/balances.py': 2,
    'config/credentials.py': 1,
    'config/doctor.py': 6,
    'config/profiles.py': 1,
    'config/settings.py': 2,
    'config/v2.py': 1,
    'conftest.py': 11,
    'connectors/architect/client.py': 2,
    'connectors/architect/service.py': 2,
    'connectors/calendar/google_calendar.py': 1,
    'connectors/calendar/oauth.py': 1,
    'connectors/calendar/server_api.py': 2,
    'connectors/contacts/oauth.py': 1,
    'connectors/email/mailbox.py': 16,
    'connectors/email/oauth.py': 1,
    'connectors/email/search.py': 2,
    'connectors/email/service.py': 6,
    'connectors/files/oauth.py': 1,
    'connectors/google/app.py': 2,
    'connectors/meshkore/bridge.py': 9,
    'connectors/meshkore/capsule.py': 2,
    'connectors/meshkore/client.py': 3,
    'connectors/meshkore/identity.py': 1,
    'connectors/meshkore/journal.py': 2,
    'connectors/meshkore/manager.py': 1,
    'connectors/meshkore/mem_ingest.py': 2,
    'connectors/meshkore/security.py': 2,
    'connectors/meshkore/server_api.py': 2,
    'connectors/messaging/__init__.py': 1,
    'connectors/messaging/archive.py': 1,
    'connectors/messaging/brief.py': 2,
    'connectors/messaging/contacts_bus.py': 3,
    'connectors/messaging/control.py': 2,
    'connectors/messaging/ingest.py': 17,
    'connectors/messaging/notify.py': 2,
    'connectors/messaging/store.py': 3,
    'connectors/messaging/triage.py': 1,
    'connectors/music/registry.py': 1,
    'connectors/oauth_callback.py': 1,
    'connectors/photos/oauth.py': 1,
    'connectors/secure_json_store.py': 2,
    'connectors/spotify/auth.py': 2,
    'connectors/telegram/service.py': 4,
    'connectors/torrent/service.py': 1,
    'connectors/torrent/session.py': 4,
    'connectors/video/oauth.py': 1,
    'connectors/video/server_api.py': 2,
    'connectors/whatsapp/__main__.py': 1,
    'connectors/whatsapp/bridge_proc.py': 1,
    'connectors/whatsapp/run.py': 1,
    'connectors/whatsapp/service.py': 2,
    'daemon/audit.py': 3,
    'daemon/config.py': 2,
    'daemon/fs/roots.py': 2,
    'daemon/http/handler.py': 2,
    'daemon/http/lifecycle.py': 1,
    'daemon/packaging/build.py': 1,
    'daemon/packaging/release_names.py': 1,
    'daemon/paths.py': 2,
    'i18n/init/detect.py': 3,
    'library/paths.py': 2,
    'library/server_api.py': 1,
    'memory/_prompt.py': 2,
    'memory/action_map_store.py': 3,
    'memory/api.py': 3,
    'memory/consolidator.py': 1,
    'memory/db.py': 4,
    'memory/embeddings.py': 5,
    'memory/episodic.py': 2,
    'memory/errands_store.py': 3,
    'memory/queue.py': 2,
    'memory/rem.py': 9,
    'memory/rerank.py': 1,
    'memory/retriever.py': 4,
    'memory/state.py': 1,
    'memory/tasks_store.py': 3,
    'memory/workflows_store.py': 3,
    'memory/writer.py': 2,
    'nucleo/actionmap/__init__.py': 1,
    'nucleo/actionmap/executor.py': 5,
    'nucleo/actionmap/store.py': 2,
    'nucleo/actionmap/watch.py': 1,
    'nucleo/agent_api.py': 4,
    'nucleo/agentes/claude_code.py': 1,
    'nucleo/agentes/code.py': 1,
    'nucleo/agentes/codex.py': 1,
    'nucleo/agentes/web.py': 9,
    'nucleo/batch/runner.py': 3,
    'nucleo/batch/split.py': 1,
    'nucleo/browser_search.py': 9,
    'nucleo/canvas_arbiter.py': 2,
    'nucleo/canvas_focus.py': 1,
    'nucleo/circuit.py': 7,
    'nucleo/context_packs/introduction.py': 2,
    'nucleo/dispatch.py': 16,
    'nucleo/dispatch_confirm.py': 1,
    'nucleo/dispatch_listener.py': 6,
    'nucleo/dispatch_prepare.py': 12,
    'nucleo/dispatch_prompts.py': 1,
    'nucleo/dispatch_session.py': 11,
    'nucleo/docsheet.py': 4,
    'nucleo/done_ops.py': 1,
    'nucleo/energy_lease.py': 1,
    'nucleo/energy_meter.py': 7,
    'nucleo/errand_continuity.py': 3,
    'nucleo/errand_kind.py': 4,
    'nucleo/errand_title.py': 1,
    'nucleo/errands/__init__.py': 4,
    'nucleo/errands/book.py': 1,
    'nucleo/errands/proposals.py': 1,
    'nucleo/errands/wake.py': 6,
    'nucleo/errands/watch.py': 5,
    'nucleo/flash/accumulator.py': 2,
    'nucleo/flash/act_repair.py': 2,
    'nucleo/flash/answer_guards.py': 1,
    'nucleo/flash/canvas_license.py': 4,
    'nucleo/flash/canvas_visibility.py': 1,
    'nucleo/flash/card_commission.py': 2,
    'nucleo/flash/commission_guards.py': 1,
    'nucleo/flash/connector_briefs.py': 5,
    'nucleo/flash/data_ops.py': 19,
    'nucleo/flash/delivery.py': 2,
    'nucleo/flash/direct_action.py': 4,
    'nucleo/flash/errand_sheet.py': 3,
    'nucleo/flash/escalate.py': 4,
    'nucleo/flash/escalation_guard.py': 2,
    'nucleo/flash/fast_client.py': 9,
    'nucleo/flash/frontend.py': 2,
    'nucleo/flash/hard_turn.py': 2,
    'nucleo/flash/harness_turn.py': 1,
    'nucleo/flash/image_turn.py': 3,
    'nucleo/flash/listing_turn.py': 4,
    'nucleo/flash/live_blocks.py': 7,
    'nucleo/flash/memory_cache.py': 4,
    'nucleo/flash/music_flow.py': 2,
    'nucleo/flash/op_receipt.py': 3,
    'nucleo/flash/post_stream_lanes.py': 3,
    'nucleo/flash/post_stream_settle.py': 3,
    'nucleo/flash/post_stream_words.py': 3,
    'nucleo/flash/presence.py': 2,
    'nucleo/flash/prewarm.py': 1,
    'nucleo/flash/probe.py': 9,
    'nucleo/flash/probe_actionmap.py': 2,
    'nucleo/flash/probe_after.py': 9,
    'nucleo/flash/probe_api.py': 2,
    'nucleo/flash/probe_before.py': 7,
    'nucleo/flash/probe_decide.py': 2,
    'nucleo/flash/probe_mirrors.py': 10,
    'nucleo/flash/probe_scheduling.py': 3,
    'nucleo/flash/prompt.py': 12,
    'nucleo/flash/provider_chain.py': 10,
    'nucleo/flash/provider_failure.py': 4,
    'nucleo/flash/reminder_guards.py': 1,
    'nucleo/flash/rule_scope.py': 2,
    'nucleo/flash/second_pass.py': 4,
    'nucleo/flash/segmenter.py': 1,
    'nucleo/flash/show_guard.py': 1,
    'nucleo/flash/show_target.py': 5,
    'nucleo/flash/smalltalk.py': 2,
    'nucleo/flash/style_directive.py': 8,
    'nucleo/flash/task_block.py': 2,
    'nucleo/flash/titular_watch.py': 4,
    'nucleo/flash/tool_executor_calls.py': 3,
    'nucleo/flash/tool_executor_widget_calls.py': 8,
    'nucleo/flash/tool_selection.py': 1,
    'nucleo/flash/turn_brief.py': 1,
    'nucleo/flash/turn_perf.py': 1,
    'nucleo/flash/vault_rules.py': 1,
    'nucleo/flash/video_turn.py': 2,
    'nucleo/flash/web_auth.py': 2,
    'nucleo/flash/widget_data_turn.py': 7,
    'nucleo/flash/widget_read.py': 5,
    'nucleo/flash/write_outcome.py': 1,
    'nucleo/harness.py': 1,
    'nucleo/homeostasis.py': 7,
    'nucleo/jev.py': 4,
    'nucleo/library_router.py': 2,
    'nucleo/listing_search.py': 2,
    'nucleo/loop.py': 17,
    'nucleo/mem_processor.py': 8,
    'nucleo/memllm.py': 5,
    'nucleo/memory_agent/dossier.py': 1,
    'nucleo/memory_agent/gates.py': 2,
    'nucleo/memory_agent/ingest.py': 2,
    'nucleo/mesh_agents.py': 2,
    'nucleo/provider_health.py': 2,
    'nucleo/rails.py': 1,
    'nucleo/rehydrate.py': 6,
    'nucleo/research.py': 1,
    'nucleo/reset.py': 1,
    'nucleo/runstate.py': 3,
    'nucleo/sandbox.py': 7,
    'nucleo/scheduler.py': 1,
    'nucleo/sheets.py': 7,
    'nucleo/spec.py': 8,
    'nucleo/susurro/apply.py': 9,
    'nucleo/susurro/engine.py': 7,
    'nucleo/tasks.py': 4,
    'nucleo/torrent_router.py': 2,
    'nucleo/turn/recall_budget.py': 5,
    'nucleo/websearch.py': 2,
    'nucleo/worker_api.py': 9,
    'nucleo/workers/claude_session.py': 11,
    'nucleo/workers/codex_session.py': 8,
    'nucleo/workers/ended.py': 2,
    'nucleo/workers/findings.py': 1,
    'nucleo/workers/generator_session.py': 4,
    'nucleo/workers/goal.py': 1,
    'nucleo/workers/grok_session.py': 3,
    'nucleo/workers/handoff.py': 1,
    'nucleo/workers/progress.py': 2,
    'nucleo/workers/providers.py': 7,
    'nucleo/workers/registry.py': 1,
    'nucleo/workers/relay.py': 1,
    'nucleo/workers/reports.py': 8,
    'nucleo/workers/resume.py': 1,
    'nucleo/workers/session.py': 16,
    'nucleo/workers/session_notes.py': 5,
    'nucleo/workers/stall.py': 2,
    'nucleo/workers/tool_steps.py': 1,
    'nucleo/workers/workdir.py': 2,
    'nucleo/workflows/domains.py': 1,
    'nucleo/workflows/store.py': 4,
    'nucleo/workspace.py': 1,
    'observability/identity.py': 6,
    'scripts/zaelar.py': 3,
    'server/__init__.py': 17,
    'server/active.py': 1,
    'server/boot.py': 2,
    'server/canvas_api.py': 10,
    'server/config_api.py': 4,
    'server/daemon_api.py': 1,
    'server/feedback_api.py': 1,
    'server/voice_api.py': 3,
    'voice/attention.py': 4,
    'voice/engine/core/accel.py': 2,
    'voice/engine/core/logging.py': 2,
    'voice/engine/llm/providers/acc_notices.py': 5,
    'voice/engine/llm/providers/confirm_gate.py': 2,
    'voice/engine/llm/providers/fast_lane.py': 15,
    'voice/engine/llm/providers/flow_lifecycle.py': 2,
    'voice/engine/llm/providers/nucleo.py': 5,
    'voice/engine/llm/providers/pending_confirm.py': 3,
    'voice/engine/llm/providers/turn_admit.py': 2,
    'voice/engine/llm/providers/turn_after.py': 6,
    'voice/engine/llm/providers/turn_failure.py': 2,
    'voice/engine/llm/providers/turn_fragment.py': 1,
    'voice/engine/llm/providers/turn_prompt.py': 1,
    'voice/engine/llm/providers/widget_intent.py': 3,
    'voice/engine/pipeline/agent.py': 4,
    'voice/engine/pipeline/agent_events.py': 12,
    'voice/engine/pipeline/instrument.py': 4,
    'voice/engine/pipeline/session_health.py': 4,
    'voice/engine/speech/elevenlabs_voices.py': 6,
    'voice/engine/speech/filler_audio.py': 9,
    'voice/engine/speech/say_numbers.py': 1,
    'voice/engine/speech/stt/whisper_local.py': 1,
    'voice/engine/speech/tts/__init__.py': 2,
    'voice/engine/speech/tts/elevenlabs.py': 1,
    'voice/engine/speech/tts/inworld.py': 1,
    'voice/engine/speech/turn/semantic.py': 2,
    'voice/engine/speech/voices.py': 3,
    'voice/interrupt_grammar.py': 1,
    'voice/mic_input.py': 2,
    'voice/observer.py': 17,
    'voice/proactive.py': 3,
    'voice/trace.py': 3,
    'widgets/__init__.py': 2,
    'widgets/agenda/gcal.py': 4,
    'widgets/agenda/index.py': 1,
    'widgets/agenda/invite.py': 1,
    'widgets/agenda/reminders.py': 1,
    'widgets/agenda/tasklists.py': 1,
    'widgets/aliases.py': 1,
    'widgets/background.py': 2,
    'widgets/brief.py': 5,
    'widgets/confirm.py': 3,
    'widgets/contactos/gcontacts.py': 2,
    'widgets/contactos/sources.py': 1,
    'widgets/contract.py': 2,
    'widgets/desktop_props.py': 2,
    'widgets/effects.py': 2,
    'widgets/generator.py': 6,
    'widgets/imagenes/data.py': 2,
    'widgets/instances.py': 1,
    'widgets/lifecycle.py': 2,
    'widgets/map/data.py': 3,
    'widgets/mensajeria/autorespond.py': 2,
    'widgets/mensajeria/data.py': 1,
    'widgets/mensajeria/outbound.py': 1,
    'widgets/mensajeria/owner.py': 2,
    'widgets/mensajeria/views.py': 1,
    'widgets/musica/data.py': 2,
    'widgets/naming.py': 3,
    'widgets/navegador/act_api.py': 11,
    'widgets/navegador/agent.py': 3,
    'widgets/navegador/click_gate.py': 2,
    'widgets/navegador/data.py': 1,
    'widgets/navegador/dom.py': 2,
    'widgets/navegador/owner.py': 21,
    'widgets/navegador/owner_actions.py': 8,
    'widgets/navegador/owner_login.py': 8,
    'widgets/navegador/owner_page.py': 4,
    'widgets/navegador/tasks.py': 5,
    'widgets/paths.py': 1,
    'widgets/producers.py': 1,
    'widgets/provenance.py': 2,
    'widgets/refs.py': 4,
    'widgets/registry.py': 1,
    'widgets/reset.py': 2,
    'widgets/results/data.py': 1,
    'widgets/results/intake.py': 1,
    'widgets/results/sheet_names.py': 1,
    'widgets/rows.py': 1,
    'widgets/runtime.py': 2,
    'widgets/server_api.py': 17,
    'widgets/store.py': 7,
    'widgets/supervisor.py': 4,
    'widgets/youtube/helpers.py': 1,
    'widgets/youtube/library.py': 1,
}


def test_no_file_gains_a_swallowed_failure():
    now = _counts()
    grown = sorted(f"{f}: {n} (was {PER_FILE.get(f, 0)})" for f, n in now.items() if n > PER_FILE.get(f, 0))
    assert not grown, ("a failure is swallowed in silence where it was not before — say what failed (`_note` / "
                       f"`emit`) instead: {grown[:12]}")


def test_the_total_only_falls():
    assert sum(_counts().values()) <= TOTAL
